services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=twitter_clone'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
