spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/twitter_clone
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
jwt:
  expiration: 1200000
  secret: ${JWT_SECRET}